### ISSUE TITLE
Handing of paths when they are the same?

### ISSUE THREAD

**Issue by ghzgod** [OFark/Compressarr#1]
Hello, love your project!

How do you handle docker paths when they are the same for both multiple containers?

Thanks in advance and keep up the good work.  Tdarr and Unmanic were just headaches for me.

**Comment by OFark** [comment]
So what happens during an import, behind the scenes, is Compressarr tell Radarr and Sonarr to look in folder x for the files, scan it and return me what you've found. Verify it's what we've just encoded and send back an OK signal. 

The folder must exist in both dockers for this to work.

For workload importing we ask Radarr/Sonarr what files you have and it passed back what it thinks is the path to the file. In your case I'm guessing /media/Movie Name/Movie Name.mkv or /media/Series/Season/Episode.mkv

Now the problem you're going to have there is you would need to map both /mnt/user/radarr_folder and /mnt/user/sonar_folder to /media in the Compressarr docker to make that work, and I don't think you can do that.

What you can do is set a base folder in Compressarr for each service. So you could map /mnt/user/radarr_folder -> /radarr/media and /mnt/user/sonar_folder => /sonarr/media
Then set the base folder for radar and sonarr to /radarr and /sonarr respectively and this (baring any spelling mistakes) should work just fine. I have tested this across OS platforms, mapping /linux mount points to Windows mapped drives and it works. 

What won't work is mapping during automatic importing, that HAS to be the same in both places, but you can set up a separate folder/map for each docker without affecting the rest of your options. E.g. ./mnt/user/Compresarrr => /Encode on each docker and use that as Compressarr's output.

**Comment by OFark** [comment]
p.s. Sorry for the delay, I've just got a new PC that needed building and overclocking, and tweaking and testing.

**Comment by ghzgod** [comment]
Hey no worries on the delay, built a few computers myself and understand setup takes time!  Thank you for the reply.  I actually got it working and it looks like your explanation is what I came to as well.  I have a lot of home videos I need to compress.  Keep up the good work!
