### ISSUE TITLE
File Filter: An error has occurred. This application may no longer respond until reloaded.

### ISSUE THREAD

**Issue by acrane1** [OFark/Compressarr#6]
When trying to do certain filters on my Movies, I'm getting this error: An error has occurred. This application may no longer respond until reloaded. [Reload]
I have not tested all the filters it gets tripped on but it happens every time with Movie File - Size(F), Movie File - Size.
I have tried Size on Disk, but that does not seem to filter anything.
INFO:
Application: 1.2.8117.21545

Runtime: 6.0.3

FFmpeg: N-101934-g7e241a1

Docker: Yes

OS: Unix 5.10.28.0 - Nvidia HW Support

OS 64bit: True

App 64bit: True

`{"Timestamp":"18:51:08 ","EventId":111,"LogLevel":"Error","Category":"Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost","Message":"Unhandled exception in circuit \u0027lhcjvRbtHxASmZ9uEHKgYiBbN32m2lwJX4uUsnHnbG8\u0027.","Exception":"System.ArgumentNullException: Value cannot be null. (Parameter \u0027method\u0027) at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1) at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable\u00601 arguments) at System.Linq.Dynamic.Core.Parser.ExpressionHelper.GenerateStaticMethodCall(String methodName, Expression left, Expression right) at System.Linq.Dynamic.Core.Parser.ExpressionHelper.GenerateGreaterThanEqual(Expression left, Expression right) at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor) at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values) at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where(IQueryable source, ParsingConfig config, String predicate, Object[] args) at Compressarr.Services.RadarrService.FilterMovies(IQueryable\u00601 movies, String filter, IEnumerable\u00601 filterValues) in /src/Compressarr/Compressarr/Services/RadarrService.cs:line 382 at Compressarr.Services.RadarrService.GetMoviesAsync(Boolean force) in /src/Compressarr/Compressarr/Services/RadarrService.cs:line 74 at Compressarr.Pages.Radarr.RefreshMovies(Object sender, EventArgs e) in /src/Compressarr/Compressarr/Pages/Radarr.razor.cs:line 289 at Compressarr.Pages.Radarr.FilterUpdate() in /src/Compressarr/Compressarr/Pages/Radarr.razor.cs:line 271 at Compressarr.Pages.Radarr.AddFilter() in /src/Compressarr/Compressarr/Pages/Radarr.razor.cs:line 117 at System.Threading.Tasks.Task.\u003C\u003Ec.\u003CThrowAsync\u003Eb__128_0(Object state) at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource\u00601 completion, SendOrPostCallback d, Object state) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)","State":{"Message":"Unhandled exception in circuit \u0027lhcjvRbtHxASmZ9uEHKgYiBbN32m2lwJX4uUsnHnbG8\u0027.","CircuitId":"lhcjvRbtHxASmZ9uEHKgYiBbN32m2lwJX4uUsnHnbG8","{OriginalFormat}":"Unhandled exception in circuit \u0027{CircuitId}\u0027."},"Scopes":[{"Message":"SpanId:05fa627b00ea531f, TraceId:2b5af0c5997916fc7287292112bb4a27, ParentId:0000000000000000","SpanId":"05fa627b00ea531f","TraceId":"2b5af0c5997916fc7287292112bb4a27","ParentId":"0000000000000000"},{"Message":"ConnectionId:0HMGCVQ72QE1P","ConnectionId":"0HMGCVQ72QE1P"},{"Message":"RequestPath:/_blazor RequestId:0HMGCVQ72QE1P:00000002","RequestId":"0HMGCVQ72QE1P:00000002","RequestPath":"/_blazor"},{"Message":"TransportConnectionId:bPMiK7iMiTPl3MJVq0cgjw","TransportConnectionId":"bPMiK7iMiTPl3MJVq0cgjw"}]}

{"Timestamp":"18:51:18 ","EventId":111,"LogLevel":"Error","Category":"Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost","Message":"Unhandled exception in circuit \u0027R3LIEJ2HgXk6fQKgT6z5sqkZQWErj5qim_mi-TD8lwk\u0027.","Exception":"System.ArgumentNullException: Value cannot be null. (Parameter \u0027method\u0027) at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1) at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable\u00601 arguments) at System.Linq.Dynamic.Core.Parser.ExpressionHelper.GenerateStaticMethodCall(String methodName, Expression left, Expression right) at System.Linq.Dynamic.Core.Parser.ExpressionHelper.GenerateGreaterThanEqual(Expression left, Expression right) at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor) at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values) at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where(IQueryable source, ParsingConfig config, String predicate, Object[] args) at Compressarr.Services.RadarrService.FilterMovies(IQueryable\u00601 movies, String filter, IEnumerable\u00601 filterValues) in /src/Compressarr/Compressarr/Services/RadarrService.cs:line 382 at Compressarr.Services.RadarrService.GetMoviesAsync(Boolean force) in /src/Compressarr/Compressarr/Services/RadarrService.cs:line 74 at Compressarr.Pages.Radarr.RefreshMovies(Object sender, EventArgs e) in /src/Compressarr/Compressarr/Pages/Radarr.razor.cs:line 289 at Compressarr.Pages.Radarr.FilterUpdate() in /src/Compressarr/Compressarr/Pages/Radarr.razor.cs:line 271 at Compressarr.Pages.Radarr.AddFilter() in /src/Compressarr/Compressarr/Pages/Radarr.razor.cs:line 117 at System.Threading.Tasks.Task.\u003C\u003Ec.\u003CThrowAsync\u003Eb__128_0(Object state) at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource\u00601 completion, SendOrPostCallback d, Object state) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)","State":{"Message":"Unhandled exception in circuit \u0027R3LIEJ2HgXk6fQKgT6z5sqkZQWErj5qim_mi-TD8lwk\u0027.","CircuitId":"R3LIEJ2HgXk6fQKgT6z5sqkZQWErj5qim_mi-TD8lwk","{OriginalFormat}":"Unhandled exception in circuit \u0027{CircuitId}\u0027."},"Scopes":[{"Message":"SpanId:c745792cbbf593c6, TraceId:3421f9d8f28228af976e0c7604be008d, ParentId:0000000000000000","SpanId":"c745792cbbf593c6","TraceId":"3421f9d8f28228af976e0c7604be008d","ParentId":"0000000000000000"},{"Message":"ConnectionId:0HMGCVQ72QE1Q","ConnectionId":"0HMGCVQ72QE1Q"},{"Message":"RequestPath:/_blazor RequestId:0HMGCVQ72QE1Q:00000002","RequestId":"0HMGCVQ72QE1Q:00000002","RequestPath":"/_blazor"},{"Message":"TransportConnectionId:IBM6Zstm2Drav6APywLepg","TransportConnectionId":"IBM6Zstm2Drav6APywLepg"}]}

{"Timestamp":"18:51:26 ","EventId":111,"LogLevel":"Error","Category":"Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost","Message":"Unhandled exception in circuit \u0027lYvoun9fsHyYvOJDQ_xkpnTElj9ru9ml4Uymh2bYJcQ\u0027.","Exception":"System.ArgumentNullException: Value cannot be null. (Parameter \u0027method\u0027) at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1) at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable\u00601 arguments) at System.Linq.Dynamic.Core.Parser.ExpressionHelper.GenerateStaticMethodCall(String methodName, Expression left, Expression right) at System.Linq.Dynamic.Core.Parser.ExpressionHelper.GenerateGreaterThanEqual(Expression left, Expression right) at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator() at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor) at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values) at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where(IQueryable source, ParsingConfig config, String predicate, Object[] args) at Compressarr.Services.RadarrService.FilterMovies(IQueryable\u00601 movies, String filter, IEnumerable\u00601 filterValues) in /src/Compressarr/Compressarr/Services/RadarrService.cs:line 382 at Compressarr.Services.RadarrService.GetMoviesAsync(Boolean force) in /src/Compressarr/Compressarr/Services/RadarrService.cs:line 74 at Compressarr.Pages.Radarr.RefreshMovies(Object sender, EventArgs e) in /src/Compressarr/Compressarr/Pages/Radarr.razor.cs:line 289 at Compressarr.Pages.Radarr.FilterUpdate() in /src/Compressarr/Compressarr/Pages/Radarr.razor.cs:line 271 at Compressarr.Pages.Radarr.AddFilter() in /src/Compressarr/Compressarr/Pages/Radarr.razor.cs:line 117 at System.Threading.Tasks.Task.\u003C\u003Ec.\u003CThrowAsync\u003Eb__128_0(Object state) at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource\u00601 completion, SendOrPostCallback d, Object state) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)","State":{"Message":"Unhandled exception in circuit \u0027lYvoun9fsHyYvOJDQ_xkpnTElj9ru9ml4Uymh2bYJcQ\u0027.","CircuitId":"lYvoun9fsHyYvOJDQ_xkpnTElj9ru9ml4Uymh2bYJcQ","{OriginalFormat}":"Unhandled exception in circuit \u0027{CircuitId}\u0027."},"Scopes":[{"Message":"SpanId:4e08bcf236db5261, TraceId:9ecb255335f6c92697995aff7eae9ddb, ParentId:0000000000000000","SpanId":"4e08bcf236db5261","TraceId":"9ecb255335f6c92697995aff7eae9ddb","ParentId":"0000000000000000"},{"Message":"ConnectionId:0HMGCVQ72QE1R","ConnectionId":"0HMGCVQ72QE1R"},{"Message":"RequestPath:/_blazor RequestId:0HMGCVQ72QE1R:00000002","RequestId":"0HMGCVQ72QE1R:00000002","RequestPath":"/_blazor"},{"Message":"TransportConnectionId:mD-iCkf_Rtfua2UcNDoaVQ","TransportConnectionId":"mD-iCkf_Rtfua2UcNDoaVQ"}]}

{"Timestamp":"18:56:11 ","EventId":111,"LogLevel":"Error","Category":"Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost","Message":"Unhandled exception in circuit \u0027He5zXvLTKQ6oculSl-5XdysLsZHmIu2ww-iH00urngU\u0027.","Exception":"System.ObjectDisposedException: Cannot access a disposed object. at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder\u00601.ThrowObjectDisposedException() at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder\u00601.GrowBuffer(Int32 desiredCapacity) at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext\u0026 diffContext, Int32 oldFrameIndex, Int32 newFrameIndex) at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext\u0026 diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl) at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange\u00601 oldTree, ArrayRange\u00601 newTree) at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception\u0026 renderFragmentException) at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()","State":{"Message":"Unhandled exception in circuit \u0027He5zXvLTKQ6oculSl-5XdysLsZHmIu2ww-iH00urngU\u0027.","CircuitId":"He5zXvLTKQ6oculSl-5XdysLsZHmIu2ww-iH00urngU","{OriginalFormat}":"Unhandled exception in circuit \u0027{CircuitId}\u0027."},"Scopes":[{"Message":"SpanId:25848a41ee846c62, TraceId:a35ce461bbb245a2d19c193cbccdd24f, ParentId:0000000000000000","SpanId":"25848a41ee846c62","TraceId":"a35ce461bbb245a2d19c193cbccdd24f","ParentId":"0000000000000000"},{"Message":"ConnectionId:0HMGCVQ72QE1S","ConnectionId":"0HMGCVQ72QE1S"},{"Message":"RequestPath:/_blazor RequestId:0HMGCVQ72QE1S:00000002","RequestId":"0HMGCVQ72QE1S:00000002","RequestPath":"/_blazor"},{"Message":"TransportConnectionId:XKUI7D_M2KQm9jXBlO_TEg","TransportConnectionId":"XKUI7D_M2KQm9jXBlO_TEg"}]}
`

**Comment by OFark** [comment]
I am assuming you're doing a greater than or less than? Can you outline exactly what you are filtering on so I can replicate it? p.s. Thanks for including the logs.

**Comment by acrane1** [comment]
This is trying to do a greater than value, and greater than or equal to. I tried doing multiple sizes, like 2, 20, 2000 etc and they all failed.

**Comment by acrane1** [comment]
I noticed I am also getting it when I search for Title doesn't contain. The filter is trying to show anything that is 1080p quality, and not any form of x265 or contain the work Potter in the title.

tamp":"18:38:43 ","EventId":0,"LogLevel":"Debug","Category":"Compressarr.Services.RadarrService","Message":"Filter: ( np(MovieFile.Quality.FileQuality.Name) == \u0022WEBDL-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022Remux-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022Bluray-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022HDTV-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022HEVC\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022x265\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022h265\u0022 ) and ( np(MovieFile.MediaInfo.VideoCodec) != \u0022h265\u0022 and np(MovieFile.MediaInfo.VideoCodec) != \u0022x265\u0022 and np(MovieFile.MediaInfo.VideoCodec) != \u0022HEVC\u0022 ) and np(Title.!Contains(@0),false)","State":{"Message":"Filter: ( np(MovieFile.Quality.FileQuality.Name) == \u0022WEBDL-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022Remux-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022Bluray-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022HDTV-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022HEVC\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022x265\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022h265\u0022 ) and ( np(MovieFile.MediaInfo.VideoCodec) != \u0022h265\u0022 and np(MovieFile.MediaInfo.VideoCodec) != \u0022x265\u0022 and np(MovieFile.MediaInfo.VideoCodec) != \u0022HEVC\u0022 ) and np(Title.!Contains(@0),false)","{OriginalFormat}":"Filter: ( np(MovieFile.Quality.FileQuality.Name) == \u0022WEBDL-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022Remux-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022Bluray-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022HDTV-1080p\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022HEVC\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022x265\u0022 or np(MovieFile.Quality.FileQuality.Name) == \u0022h265\u0022 ) and ( np(MovieFile.MediaInfo.VideoCodec) != \u0022h265\u0022 and np(MovieFile.MediaInfo.VideoCodec) != \u0022x265\u0022 and np(MovieFile.MediaInfo.VideoCodec) != \u0022HEVC\u0022 ) and np(Title.!Contains(@0),false)"},"Scopes":[{"Message":"SpanId:45829b44e75c876f, TraceId:ef4e1ad82df3cfc0a9b92cfacfef4bc3, ParentId:0000000000000000","SpanId":"45829b44e75c876f","TraceId":"ef4e1ad82df3cfc0a9b92cfacfef4bc3","ParentId":"0000000000000000"},{"Message":"ConnectionId:0HMGIACD6AG2M","ConnectionId":"0HMGIACD6AG2M"},{"Message":"RequestPath:/_blazor RequestId:0HMGIACD6AG2M:00000002","RequestId":"0HMGIACD6AG2M:00000002","RequestPath":"/_blazor"},{"Message":"TransportConnectionId:Ssr_FDgAfmh2fJoW0TjsSA","TransportConnectionId":"Ssr_FDgAfmh2fJoW0TjsSA"},"Get Movies"]}
{"Timestamp":"18:38:43 ","EventId":0,"LogLevel":"Debug","Category":"Compressarr.Services.RadarrService","Message":"Filter Values: Potter","State":{"Message":"Filter Values: Potter","{OriginalFormat}":"Filter Values: Potter"},"Scopes":[{"Message":"SpanId:45829b44e75c876f, TraceId:ef4e1ad82df3cfc0a9b92cfacfef4bc3, ParentId:0000000000000000","SpanId":"45829b44e75c876f","TraceId":"ef4e1ad82df3cfc0a9b92cfacfef4bc3","ParentId":"0000000000000000"},{"Message":"ConnectionId:0HMGIACD6AG2M","ConnectionId":"0HMGIACD6AG2M"},{"Message":"RequestPath:/_blazor RequestId:0HMGIACD6AG2M:00000002","RequestId":"0HMGIACD6AG2M:00000002","RequestPath":"/_blazor"},{"Message":"TransportConnectionId:Ssr_FDgAfmh2fJoW0TjsSA","TransportConnectionId":"Ssr_FDgAfmh2fJoW0TjsSA"},"Get Movies"]}
{"Timestamp":"18:38:43 ","EventId":111,"LogLevel":"Error","Category":"Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost","Message":"Unhandled exception in circuit \u00272Zn4M3Pf1EmQMqWj07AZiSQ8piBu2JMHnGVpa-WfmfY\u0027.","Exception":"Identifier expected (at index 557)","State":{"Message":"Unhandled exception in circuit \u00272Zn4M3Pf1EmQMqWj07AZiSQ8piBu2JMHnGVpa-WfmfY\u0027.","CircuitId":"2Zn4M3Pf1EmQMqWj07AZiSQ8piBu2JMHnGVpa-WfmfY","{OriginalFormat}":"Unhandled exception in circuit \u0027{CircuitId}\u0027."},"Scopes":[{"Message":"SpanId:45829b44e75c876f, TraceId:ef4e1ad82df3cfc0a9b92cfacfef4bc3, ParentId:0000000000000000","SpanId":"45829b44e75c876f","TraceId":"ef4e1ad82df3cfc0a9b92cfacfef4bc3","ParentId":"0000000000000000"},{"Message":"ConnectionId:0HMGIACD6AG2M","ConnectionId":"0HMGIACD6AG2M"},{"Message":"RequestPath:/_blazor RequestId:0HMGIACD6AG2M:00000002","RequestId":"0HMGIACD6AG2M:00000002","RequestPath":"/_blazor"},{"Message":"TransportConnectionId:Ssr_FDgAfmh2fJoW0TjsSA","TransportConnectionId":"Ssr_FDgAfmh2fJoW0TjsSA"}]}

**Comment by OFark** [comment]
Ok, I can see the same problem here, thanks for that I'll have a look when I get a moment.

**Comment by OFark** [comment]
I have fixed these bugs (thank you) and just pushed a release, it's building now. 
I cannot find an issue with Size or SizeonDisk, they seem to be working ok. 
Can you try it again and let me know.

**Comment by acrane1** [comment]
Thanks, I'm no longer getting an error/ having the UI crash. Though the Size filter doesn't seem to work. Unless I'm miss understanding the value for size. Is the filter in Bytes? I added these filters 1 by 1, to see if I'd get a response. Wasn't until the last one that I got it to remove a file. 
![20220404235754815](https://user-images.githubusercontent.com/6483954/161652723-9f5d6faa-59e5-434b-aacd-57140f2f1b26.jpeg)
.

**Comment by OFark** [comment]
If you double click a value on the table, so the 3.50GB for example, it'll fill the filter in for you. You should be able to see then what sort of numbers you are dealing with. 
Maybe: Feature request; have the size columns work with human strings. ie 3GB... hmmm.
