### ISSUE TITLE
No EXE in windows zip

### ISSUE THREAD

**Issue by Collcroc123** [OFark/Compressarr#8]
The instructions says I just need to launch the .exe but I can't seem to find any .exe files in the release zip, where can I find it?
![image](https://user-images.githubusercontent.com/32398853/223226116-be5c5a7c-e294-4ae5-9a4a-91c0f086dee8.png)

**Comment by OFark** [comment]
For some reason, that I can't see, the GitHub build action is removing the .exe from the file. Rename the Compressor file, the one at the top of your image, and add the .exe to the end.

**Comment by Collcroc123** [comment]
That was actually the first thing that I had tried, but when I run that file it just pops up with a small blue window that says "This app can't run on your PC To find a version for your PC, check with the software publisher."

**Comment by OFark** [comment]
Seems the release was the Linux version. Kinda makes sense, it designed to run as a Docker. I have created a new build action that will create a Compressarr-version-win.zip release.
